/**
 * Supabase `Database` types.
 *
 * Normally generated by `pnpm db:types` (supabase gen types typescript). The
 * project isn't linked for codegen yet, so the tables below are maintained by
 * hand and kept in sync with the live schema. When codegen is wired up, this
 * file should be regenerated — until then, add new tables here additively.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      /**
       * Public signup list. RLS: INSERT-only for anon/authenticated, no SELECT.
       * `email` is unique (+ a format check); `source` tags the entry point.
       */
      waitlist: {
        Row: {
          id: string
          email: string
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          source?: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          source?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
