/**
 * Generated by `pnpm db:types` (supabase gen types typescript).
 * Do not edit by hand — regenerate after every schema change.
 *
 * Placeholder until the Supabase project is linked.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
